import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "./context-api/providers";
import Header from "./components/layout/header";
import Sidebar from "./components/layout/sidebar";
import Footer from "./components/layout/footer";
import { Lobster } from "next/font/google";

const lobster = Lobster({
  weight: "400",
  variable: "--font-lobster",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KaraVoice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={`${lobster.variable} ${geistSans.variable} antialiased`}>
        <MenuProvider>
          <Header />
          <Sidebar />
        </MenuProvider>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
