import type { Metadata } from "next";
import "./globals.css";
import { MenuProvider } from "./context-api/providers";
import Header from "./components/layout/header";
import Sidebar from "./components/layout/sidebar";
import Footer from "./components/layout/footer";
import { Permanent_Marker } from "next/font/google";
import { Roboto } from "next/font/google";

const permanentMarker = Permanent_Marker({
  weight: "400",
  variable: "--font-permanent_marker",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KaraVoice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${roboto.variable} ${permanentMarker.variable} antialiased`}
      >
        <MenuProvider>
          <Header />
          <Sidebar />
        </MenuProvider>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
